// "use client"
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Heaader from "@/components/header/common";
import Cursor from "@/components/cursor/index"
import Footer from "@/components/footer/common";
import Loader from "@/components/loader/index"

const inter = Inter({ subsets: ["latin"] });
const dmsans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmsans.className}>
        <Loader />
        <Heaader />
        <Cursor />
        {children}
        <Footer />
      </body>
    </html>
  );
}
